name: Barrels
description: A better way of storing items.
authors: [John000708, TheBusyBiscuit, JustMango]
version: ${project.version}

main: com.justmangostudio.barrels.Barrels
api-version: 1.15

depend: [Slimefun]